### ISSUE TITLE
Backtabbing highlighted text hangs emacs (Jade-mode)

### ISSUE THREAD

**Issue by ProjectFrank** [brianc/jade-mode#27] opened 2014-11-06 20:56 UTC
Running Emacs 24.3.92.1

**Comment by tjefferson08** [comment] 2015-01-09 14:18
+1, it looks like the bug is reproducible in sws-mode, from which jade-mode is derived. I'm working on a fix (by removing the dependency on sws-mode and writing custom indentation functions)

**Comment by Sterlingg** [comment] 2015-01-10 23:29
I've made PR #28 to fix the original indent function in the meantime, while @tjefferson08 redoes the indentation functions

**Comment by tjefferson08** [comment] 2015-03-09 04:00
Fixed in PR #30, let's close this sucka!

**Closed** 2015-03-15 17:30 UTC
